### ISSUE TITLE
README makes no sense?

### ISSUE THREAD

**Issue by andresriancho** [ecbftw/nanown#3]
> Run the sampler to collect at least 50,000 samples for each the train, test and train_null data sets (150,000 samples total).  NOTE: Your sampler script must be run as `root` so it can tweak local networking settings and sniff packets.

Does that even make sense?

**Comment by ecbftw** [comment]
Which part doesn't make sense to you? =P

Yes, root access is needed, unfortunately, because of the need to sniff the network, manage process affinity, real-time privileges, and a few other kernel settings.  There's probably some more elegant way to deal with these and drop privileges when needed, but the code needs a lot more polishing in other areas first.  If you want to look at some of the things that require privileges, see 
lib/nanownlib/platform.py and src/listen.c .

As for the number of samples, yes you need quite a few to run reliable training and test bootstrapping.  You could try to go with less and see if it works, but the reliability of the statistics will decrease in potentially unpredictable ways.  In the future, as the statistical techniques improve, hopefully we'll need less data up front to train/test classifiers.

**Comment by andresriancho** [comment]
> 50,000 samples for each the train, test and train_null data sets 

That doesn't sound right, at least the grammar (not a native speaker, so I might be wrong)

**Comment by ecbftw** [comment]
Ok, I see what you mean.  Fixed in 49a25ca222c0d292783532ff2f2115455cfb19b8, along with some added references now that they are posted.
