### ISSUE TITLE
CPU affinity

### ISSUE THREAD

**Issue by andresriancho** [ecbftw/nanown#6]
Does setting CPU affinity for the sampler make sense? The objective would be to get better timings, but those come from the pcap lib?

https://github.com/ecbftw/nanown/blob/f05ef22feae55799c3d1ae5ccdc1ff0d3621873e/trunk/lib/nanownlib/platform.py#L4-L10

**Comment by ecbftw** [comment]
Hi Andres,

Yes, I did find setting the affinity during collection improves the results.  The reason is a bit complex, and I'm going from my own recollection here, but let me take a stab at it:

The raw time stamps are indeed set by the ethernet card upon receipt of packets using it's own internal clock.  Each CPU core has it's own clock as well.  These clocks tend to drift... they aren't synchronized with each other at the hardware level.  Instead, the kernel keeps track of how skewed each hardware clock is and adjusts timestamps it reports accordingly to stay on track with "true" time.

When you capture timestamps with pcap, you can specify the timestamp source (CPU vs network card, etc).  When pulling timestamps from the network card, you can use either PCAP_TSTAMP_ADAPTER or PCAP_TSTAMP_ADAPTER_UNSYNCED.  In the former case, the timestamp is collected from the adapter, then adjusted based on how much the kernel thinks the network card clock is skewed.  When it does this, I believe it makes the adjustment based on which CPU core clock the interrupt was received on.  So if your sniffer is moving from one core to another now and then, it seems to throw off your results a little.  But I'm very fuzzy on the details here.  Bottom line is, if you're using PCAP_TSTAMP_ADAPTER, I found through experimentation that setting the CPU affinity improves the data set.

I have read that PCAP_TSTAMP_ADAPTER_UNSYNCED is "better" because it doesn't rely on the kernel potentially screwing up your raw timestamps.  However, when I tried using it, the adapter's clock was clearly very skewed and my results drifted badly.  I imagine there would be a way to fix the results using a simple linear adjustment after the fact, but I didn't try to tackle that problem.  So my current best work around is to let the kernel do that job, but stick to a single core's clock to mitigate the kernel's contribution to noisy data.

**Comment by andresriancho** [comment]
But [this](https://github.com/ecbftw/nanown/blob/f05ef22feae55799c3d1ae5ccdc1ff0d3621873e/trunk/lib/nanownlib/platform.py#L4-L10) call will set cpu affinity for the sampler process, not the sniffer.

**Comment by ecbftw** [comment]
Yes, but child processes inherit the parent's affinity.  

I was trying to minimize C code and also experiment with things.  For instance, I had experimented with running sampler on one core and sniffer on another core, to hopefully reduce any interference the sampler introduced on the sniffer's results.  I don't think it made any difference for me, and that makes sense, because it doesn't matter so much when the sniffer receives packets as when the network card does.

**Comment by andresriancho** [comment]
> Yes, but child processes inherit the parent's affinity.

Ah! That was the detail I was unaware of. Thanks!
